/**
 * AccessCredential Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AccessCredentialEntity } from "@tidecove/core/entitlements/models/index.js";
import { entitlementsSchemas } from "@tidecove/core/entitlements";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ent";

export function createAccessCredential(overrides: Partial<AccessCredentialEntity> = {}) {
  const raw = {
    id: overrides.id ?? `acr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    entitlementId: overrides.entitlementId ?? faker.lorem.sentence(),
    expiresAt: overrides.expiresAt ?? new Date().toISOString(),
    tokenHint: overrides.tokenHint ?? faker.lorem.word(),
    ...overrides,
  };

  return entitlementsSchemas.AccessCredential.parse(raw);
}

export function accessCredentialBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAccessCredential(overrides));
}
