/**
 * ListDispute DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDisputesParams } from "@tidecove/core/participants";

export function createListDisputeRequest(overrides: Partial<ListDisputesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
