/**
 * ExecuteListComplianceTags - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListComplianceTags Use Case
 *
 * DDD: Application use case for list ComplianceTag.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListComplianceTagsInput, ListComplianceTagsOutput } from "../dto/compliance-tag.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { ComplianceTagRepository } from "../ports";

export class ExecuteListComplianceTags {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complianceTag: ComplianceTagRepository
  ) {}

  async execute(input: ListComplianceTagsInput): Promise<ListComplianceTagsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmpId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.complianceTag.listComplianceTags({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListComplianceTagsOutput;
  }
}
