/**
 * ExecuteCreateComplianceTag - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateComplianceTag Use Case
 *
 * DDD: Application use case for create ComplianceTag.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateComplianceTagInput, CreateComplianceTagOutput } from "../dto/compliance-tag.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { ComplianceTagRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateComplianceTag {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complianceTag: ComplianceTagRepository
  ) {}

  async execute(input: CreateComplianceTagInput): Promise<CreateComplianceTagOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmpId();

    // All field names extracted from OpenAPI spec: assetId, lawfulBasis, personalData, purposeTags
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.assetId) {
      throw new ValidationError("assetId is required");
    }
    if (!input.purposeTags) {
      throw new ValidationError("purposeTags is required");
    }
    if (!input.lawfulBasis) {
      throw new ValidationError("lawfulBasis is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (compliance domain)
    const entityId = this.idGenerator.cmpId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.complianceTag.createComplianceTag({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateComplianceTagOutput;
  }
}
