/**
 * KeeperPenaltyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KeeperPenaltyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KeeperPenaltyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KeeperPenaltyRepository,
} from "@tidecove/services/keepers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KeeperPenaltyRepositoryDdb } from "./keeper-penalty-repository.ddb.js";

/**
 * KeeperPenaltyRepositoryAdapter
 *
 * Implements KeeperPenaltyRepository port for infrastructure layer.
 */
export class KeeperPenaltyRepositoryAdapter implements KeeperPenaltyRepository {
  private readonly ddb: KeeperPenaltyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KeeperPenaltyRepositoryDdb(this.dynamoClient);
  }

  async listKeeperPenalties(input: Parameters<KeeperPenaltyRepository['listKeeperPenalties']>[0]): Promise<Awaited<ReturnType<KeeperPenaltyRepository['listKeeperPenalties']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listKeeperPenalties(input);
  }

  async createKeeperPenalty(input: Parameters<KeeperPenaltyRepository['createKeeperPenalty']>[0]): Promise<Awaited<ReturnType<KeeperPenaltyRepository['createKeeperPenalty']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createKeeperPenalty(input);
  }
}
