/**
 * KeeperAttestationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KeeperAttestationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KeeperAttestationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KeeperAttestationRepository,
} from "@tidecove/services/keepers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KeeperAttestationRepositoryDdb } from "./keeper-attestation-repository.ddb.js";

/**
 * KeeperAttestationRepositoryAdapter
 *
 * Implements KeeperAttestationRepository port for infrastructure layer.
 */
export class KeeperAttestationRepositoryAdapter implements KeeperAttestationRepository {
  private readonly ddb: KeeperAttestationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KeeperAttestationRepositoryDdb(this.dynamoClient);
  }

  async listKeeperAttestations(input: Parameters<KeeperAttestationRepository['listKeeperAttestations']>[0]): Promise<Awaited<ReturnType<KeeperAttestationRepository['listKeeperAttestations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listKeeperAttestations(input);
  }

  async submitKeeperAttestation(input: Parameters<KeeperAttestationRepository['submitKeeperAttestation']>[0]): Promise<Awaited<ReturnType<KeeperAttestationRepository['submitKeeperAttestation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitKeeperAttestation(input);
  }
}
