/**
 * EntitlementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EntitlementRepository Port
 *
 * DDD: Application port for entitlementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEntitlementInput, GetEntitlementOutput, ListEntitlementsInput, ListEntitlementsOutput, PurchaseEntitlementInput, PurchaseEntitlementOutput } from "../dto/entitlement.dto";
export interface EntitlementRepository {
  listEntitlements(input: ListEntitlementsInput): Promise<ListEntitlementsOutput>;
  purchaseEntitlement(input: PurchaseEntitlementInput): Promise<PurchaseEntitlementOutput>;
  getEntitlement(input: GetEntitlementInput): Promise<GetEntitlementOutput>;
}

export type { GetEntitlementInput, GetEntitlementOutput, ListEntitlementsInput, ListEntitlementsOutput, PurchaseEntitlementInput, PurchaseEntitlementOutput } from "../dto/entitlement.dto";
