/**
 * KeeperAttestation Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { KeeperAttestationEntity } from "@tidecove/core/keepers/models/index.js";
import { keepersSchemas } from "@tidecove/core/keepers";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "kpr";

export function createKeeperAttestation(overrides: Partial<KeeperAttestationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `kpr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    accepted: overrides.accepted ?? faker.datatype.boolean(),
    assetId: overrides.assetId ?? faker.string.uuid(),
    attestationType: overrides.attestationType ?? "availability",
    keeperParticipantId: overrides.keeperParticipantId ?? faker.string.uuid(),
    ...overrides,
  };

  return keepersSchemas.KeeperAttestation.parse(raw);
}

export function keeperAttestationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createKeeperAttestation(overrides));
}
