/**
 * ComputeJob Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/entitlements.openapi.types.js";
import { schemas } from "../schemas/entitlements.schemas.js";

/**
 * Entity: ComputeJobEntity
 * Description: Represents the ComputeJob domain model.
 * Source: schemas.ComputeJob
 * Type: Persisted Entity (x-dynamodb)
 */
export const ComputeJobEntitySchema = schemas.ComputeJob;
export type ComputeJobEntity = components["schemas"]["ComputeJob"];
