/**
 * Entitlement Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/entitlements.openapi.types.js";
import { schemas } from "../schemas/entitlements.schemas.js";

/**
 * Entity: EntitlementEntity
 * Description: Represents the Entitlement domain model.
 * Source: schemas.Entitlement
 * Type: Persisted Entity (x-dynamodb)
 */
export const EntitlementEntitySchema = schemas.Entitlement;
export type EntitlementEntity = components["schemas"]["Entitlement"];
