/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-asset.handler.test.js";
export * from "./list-assets.handler.test.js";
export * from "./publish-asset.handler.test.js";
export * from "./update-asset.handler.test.js";
