/**
 * UpdateAsset handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateAsset } from "@tidecove/api-server/domains/assets/handlers";
import type { AssetsDDDDependencies } from "@tidecove/api-server/domains/assets";
import { createAsset as createAssetEntity } from "@tidecove/factories/assets";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { ASSETS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateAsset", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssetsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssetsDDDDependencies>(
      ASSETS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createAssetEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { assetId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateAsset, "execute").mockResolvedValue(useCaseResult);

    await updateAsset(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateAsset.execute).toHaveBeenCalledWith(expect.objectContaining({ assetId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
