/**
 * MarketplaceFront DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketplaceFront DTOs
 *
 * DDD: Application DTOs for MarketplaceFront use cases.
 */

import type { GetMarketplaceFrontParams, ListMarketplaceFrontsParams, RegisterMarketplaceFrontRequestInput, UpdateMarketplaceFrontParams, UpdateMarketplaceFrontRequestInput } from "@tidecove/core/marketplace/types";

export type ListMarketplaceFrontsInput = ListMarketplaceFrontsParams;

export type RegisterMarketplaceFrontInput = RegisterMarketplaceFrontRequestInput;

export type GetMarketplaceFrontInput = GetMarketplaceFrontParams;

export type UpdateMarketplaceFrontInput = UpdateMarketplaceFrontParams & UpdateMarketplaceFrontRequestInput;

export type ListMarketplaceFrontsOutput = {};

export type RegisterMarketplaceFrontOutput = {};

export type GetMarketplaceFrontOutput = {};

export type UpdateMarketplaceFrontOutput = {};
