/**
 * Resolve Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ResolveEntity } from "@tidecove/core/participants/models/index.js";
import { participantsSchemas } from "@tidecove/core/participants";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ptc";

export function createResolve(overrides: Partial<ResolveEntity> = {}) {
  const raw = {
    id: overrides.id ?? `dsp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    openedByParticipantId: overrides.openedByParticipantId ?? faker.string.uuid(),
    status: overrides.status ?? "open",
    subjectId: overrides.subjectId ?? faker.string.uuid(),
    subjectType: overrides.subjectType ?? "entitlement",
    ...overrides,
  };

  return participantsSchemas.Dispute.parse(raw);
}

export function resolveBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createResolve(overrides));
}
