/**
 * Entitlement Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EntitlementEntity } from "@tidecove/core/entitlements/models/index.js";
import { entitlementsSchemas } from "@tidecove/core/entitlements";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ent";

export function createEntitlement(overrides: Partial<EntitlementEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ent_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    buyerParticipantId: overrides.buyerParticipantId ?? faker.string.uuid(),
    offerId: overrides.offerId ?? faker.string.uuid(),
    status: overrides.status ?? "pending",
    validUntil: overrides.validUntil ?? new Date().toISOString(),
    ...overrides,
  };

  return entitlementsSchemas.Entitlement.parse(raw);
}

export function entitlementBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEntitlement(overrides));
}
