/**
 * GetAsset DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAssetParams } from "@tidecove/core/assets";

export function createGetAssetRequest(overrides: Partial<GetAssetParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
