/**
 * CreateKeeperPenalty handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createKeeperPenalty } from "@tidecove/api-server/domains/keepers/handlers";
import type { KeepersDDDDependencies } from "@tidecove/api-server/domains/keepers";
import { createKeeperPenalty as createKeeperPenaltyEntity } from "@tidecove/factories/keepers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { KEEPERS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateKeeperPenalty", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: KeepersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<KeepersDDDDependencies>(
      KEEPERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createKeeperPenaltyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateKeeperPenalty, "execute").mockResolvedValue(useCaseResult);

    await createKeeperPenalty(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateKeeperPenalty.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
