/**
 * ComplianceTag DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplianceTag DTOs
 *
 * DDD: Application DTOs for ComplianceTag use cases.
 */

import type { CreateComplianceTagRequestInput, GetComplianceTagParams, ListComplianceTagsParams, UpdateComplianceTagParams, UpdateComplianceTagRequestInput } from "@tidecove/core/compliance/types";

export type ListComplianceTagsInput = ListComplianceTagsParams;

export type CreateComplianceTagInput = CreateComplianceTagRequestInput;

export type GetComplianceTagInput = GetComplianceTagParams;

export type UpdateComplianceTagInput = UpdateComplianceTagParams & UpdateComplianceTagRequestInput;

export type ListComplianceTagsOutput = {};

export type CreateComplianceTagOutput = {};

export type GetComplianceTagOutput = {};

export type UpdateComplianceTagOutput = {};
