/**
 * Decision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decision DTOs
 *
 * DDD: Application DTOs for Decision use cases.
 */

import type { ListPurposeGateDecisionsParams } from "@tidecove/core/compliance/types";

export type ListPurposeGateDecisionsInput = ListPurposeGateDecisionsParams;

export type ListPurposeGateDecisionsOutput = {};
