/**
 * AccessCredentialRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccessCredentialRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AccessCredentialRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AccessCredentialRepository,
} from "@tidecove/services/entitlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AccessCredentialRepositoryDdb } from "./access-credential-repository.ddb.js";

/**
 * AccessCredentialRepositoryAdapter
 *
 * Implements AccessCredentialRepository port for infrastructure layer.
 */
export class AccessCredentialRepositoryAdapter implements AccessCredentialRepository {
  private readonly ddb: AccessCredentialRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AccessCredentialRepositoryDdb(this.dynamoClient);
  }

  async getAccessCredential(input: Parameters<AccessCredentialRepository['getAccessCredential']>[0]): Promise<Awaited<ReturnType<AccessCredentialRepository['getAccessCredential']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAccessCredential(input);
  }
}
