/**
 * ComputeJobRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComputeJobRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ComputeJobRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ComputeJobRepository,
} from "@tidecove/services/entitlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ComputeJobRepositoryDdb } from "./compute-job-repository.ddb.js";

/**
 * ComputeJobRepositoryAdapter
 *
 * Implements ComputeJobRepository port for infrastructure layer.
 */
export class ComputeJobRepositoryAdapter implements ComputeJobRepository {
  private readonly ddb: ComputeJobRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ComputeJobRepositoryDdb(this.dynamoClient);
  }

  async listComputeJobs(input: Parameters<ComputeJobRepository['listComputeJobs']>[0]): Promise<Awaited<ReturnType<ComputeJobRepository['listComputeJobs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listComputeJobs(input);
  }

  async scheduleComputeJob(input: Parameters<ComputeJobRepository['scheduleComputeJob']>[0]): Promise<Awaited<ReturnType<ComputeJobRepository['scheduleComputeJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.scheduleComputeJob(input);
  }

  async getComputeJob(input: Parameters<ComputeJobRepository['getComputeJob']>[0]): Promise<Awaited<ReturnType<ComputeJobRepository['getComputeJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getComputeJob(input);
  }

  async cancelComputeJob(input: Parameters<ComputeJobRepository['cancelComputeJob']>[0]): Promise<Awaited<ReturnType<ComputeJobRepository['cancelComputeJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.cancelComputeJob(input);
  }
}
