/**
 * GetEntitlement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetEntitlementParams } from "@tidecove/core/entitlements";

export function createGetEntitlementRequest(overrides: Partial<GetEntitlementParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
