/**
 * ListEntitlement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEntitlementsParams } from "@tidecove/core/entitlements";

export function createListEntitlementRequest(overrides: Partial<ListEntitlementsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
