/**
 * Repository interface for KeeperAttestation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  KeeperAttestationEntity
} from "../models/keeper-attestation.entity.js";
import type {
  ListKeeperAttestationsParams,
  KeeperAttestation
} from "../types/index.js";
/**
 * KeeperAttestationRepository Interface
 */
export interface KeeperAttestationRepository extends CreateReadRepository<KeeperAttestationEntity, KeeperAttestation, string, ListKeeperAttestationsParams> {

}
