/**
 * Settlements DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Settlements Domain Module - Composition root
 *
 * DDD: Composition root for settlements domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  SettlementRepositoryAdapter,
} from "@tidecove/adapters/settlements";
import { getIdGeneratorService } from "@tidecove/adapters";
import type { AdapterDynamoDBClient } from "@tidecove/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGenerateSettlementStatement,
  ExecuteGetSettlementStatement,
  ExecuteListSettlementStatements,
} from "@tidecove/services/settlements/usecases";
// Ports (interfaces)
import type {
  SettlementRepository,
} from "@tidecove/services/settlements/ports";

export interface SettlementsDomainModule {
  repos: {
    settlements: SettlementRepository;
  };
  useCases: {
    settlements: {
      get: ExecuteGetSettlementStatement;
      list: ExecuteListSettlementStatements;
    };
  };
}

export function buildSettlementsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SettlementsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      settlements?: SettlementRepository;
    } = {};

    obj.settlements = new SettlementRepositoryAdapter(dynamoClient);
    return {
      settlements: obj.settlements!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    settlements: {
      get: new ExecuteGetSettlementStatement(executionContext, idGenerator, repos.settlements),
      list: new ExecuteListSettlementStatements(executionContext, idGenerator, repos.settlements),
    },
  };
  return { repos, useCases: useCases as SettlementsDomainModule["useCases"] };
}
