/**
 * Repository interface for AccessCredential
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AccessCredentialEntity
} from "../models/access-credential.entity.js";
/**
 * AccessCredentialRepository Interface
 */
export interface AccessCredentialRepository extends ReadRepository<AccessCredentialEntity, string, Record<string, never>> {

}
