/**
 * Repository interface for Entitlement
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EntitlementEntity
} from "../models/entitlement.entity.js";
import type {
  ListEntitlementsParams,
  Entitlement
} from "../types/index.js";
/**
 * EntitlementRepository Interface
 */
export interface EntitlementRepository extends CreateReadRepository<EntitlementEntity, Entitlement, string, ListEntitlementsParams> {

}
