/**
 * Handlers for Dispute
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ParticipantsDomainModule } from "../dependencies/participants-ddd.dependencies.js";
import type { ListDisputesInput, OpenDisputeInput } from "@tidecove/services/participants";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/disputes
 * Operation: listDisputes
 */
export async function listDisputes(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDisputesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.disputes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/disputes
 * Operation: openDispute
 */
export async function openDispute(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenDisputeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disputes.get.execute(input);
  return reply.code(201).send(result);
}


