/**
 * Handlers for Resolve
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ParticipantsDomainModule } from "../dependencies/participants-ddd.dependencies.js";
import type { ResolveDisputeInput } from "@tidecove/services/participants";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/disputes/{disputeId}/resolve
 * Operation: resolveDispute
 */
export async function resolveDispute(
  request: FastifyRequest<{ Params: { disputeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ResolveDisputeInput = {
    disputeId: request.params.disputeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.resolves.get.execute(input);
  return reply.code(200).send(result);
}


