/**
 * Asset Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/assets.openapi.types.js";
import { schemas } from "../schemas/assets.schemas.js";

/**
 * Entity: AssetEntity
 * Description: Represents the Asset domain model.
 * Source: schemas.Asset
 * Type: Persisted Entity (x-dynamodb)
 */
export const AssetEntitySchema = schemas.Asset;
export type AssetEntity = components["schemas"]["Asset"];
