/**
 * ComputeJob DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComputeJob DTOs
 *
 * DDD: Application DTOs for ComputeJob use cases.
 */

import type { CancelComputeJobParams, GetComputeJobParams, ListComputeJobsParams, ScheduleComputeJobRequestInput } from "@tidecove/core/entitlements/types";

export type ListComputeJobsInput = ListComputeJobsParams;

export type ScheduleComputeJobInput = ScheduleComputeJobRequestInput;

export type GetComputeJobInput = GetComputeJobParams;

export type CancelComputeJobInput = CancelComputeJobParams;

export type ListComputeJobsOutput = {};

export type ScheduleComputeJobOutput = {};

export type GetComputeJobOutput = {};

export type CancelComputeJobOutput = {};
