/**
 * Entitlement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Entitlement DTOs
 *
 * DDD: Application DTOs for Entitlement use cases.
 */

import type { GetEntitlementParams, ListEntitlementsParams, PurchaseEntitlementRequestInput } from "@tidecove/core/entitlements/types";

export type ListEntitlementsInput = ListEntitlementsParams;

export type PurchaseEntitlementInput = PurchaseEntitlementRequestInput;

export type GetEntitlementInput = GetEntitlementParams;

export type ListEntitlementsOutput = {};

export type PurchaseEntitlementOutput = {};

export type GetEntitlementOutput = {};
