/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as assetsRoutes from "../../domains/assets/routes/index.js";
import * as complianceRoutes from "../../domains/compliance/routes/index.js";
import * as entitlementsRoutes from "../../domains/entitlements/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as keepersRoutes from "../../domains/keepers/routes/index.js";
import * as licencesRoutes from "../../domains/licences/routes/index.js";
import * as marketplaceRoutes from "../../domains/marketplace/routes/index.js";
import * as participantsRoutes from "../../domains/participants/routes/index.js";
import * as settlementsRoutes from "../../domains/settlements/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "assets", mod: assetsRoutes },
  { domain: "compliance", mod: complianceRoutes },
  { domain: "entitlements", mod: entitlementsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "keepers", mod: keepersRoutes },
  { domain: "licences", mod: licencesRoutes },
  { domain: "marketplace", mod: marketplaceRoutes },
  { domain: "participants", mod: participantsRoutes },
  { domain: "settlements", mod: settlementsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
