/**
 * GetComplianceTag DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetComplianceTagParams } from "@tidecove/core/compliance";

export function createGetComplianceTagRequest(overrides: Partial<GetComplianceTagParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
