/**
 * Routes for LicenceOffer
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { amendLicenceOffer, createLicenceOffer, getLicenceOffer, listLicenceOffers } from "../handlers/licence-offer.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function licenceOfferRoutes(fastify: FastifyInstance) {
  // POST /v1/licence-offers (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/licence-offers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLicencesDependenciesForRequest();
        await createLicenceOffer(request, reply, deps);
      });
    }
  );


  // GET /v1/licence-offers (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/licence-offers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLicencesDependenciesForRequest();
        await listLicenceOffers(request, reply, deps);
      });
    }
  );


  // PATCH /v1/licence-offers/{offerId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/licence-offers/:offerId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLicencesDependenciesForRequest();
        await amendLicenceOffer(request, reply, deps);
      });
    }
  );


  // GET /v1/licence-offers/{offerId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/licence-offers/:offerId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLicencesDependenciesForRequest();
        await getLicenceOffer(request, reply, deps);
      });
    }
  );


}
