/**
 * Routes for ComplianceTag
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createComplianceTag, getComplianceTag, listComplianceTags, updateComplianceTag } from "../handlers/compliance-tag.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function complianceTagRoutes(fastify: FastifyInstance) {
  // POST /v1/compliance-tags (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/compliance-tags",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getComplianceDependenciesForRequest();
        await createComplianceTag(request, reply, deps);
      });
    }
  );


  // GET /v1/compliance-tags (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/compliance-tags",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getComplianceDependenciesForRequest();
        await listComplianceTags(request, reply, deps);
      });
    }
  );


  // GET /v1/compliance-tags/{tagId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/compliance-tags/:tagId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { tagId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getComplianceDependenciesForRequest();
        await getComplianceTag(request, reply, deps);
      });
    }
  );


  // PATCH /v1/compliance-tags/{tagId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/compliance-tags/:tagId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { tagId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getComplianceDependenciesForRequest();
        await updateComplianceTag(request, reply, deps);
      });
    }
  );


}
