/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Keepers Domain Use Cases
 * 
 * List of all use case names for the keepers domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const KEEPERS_USE_CASES = [
  "executeCreateKeeperPenalty",
  "executeListKeeperAttestations",
  "executeListKeeperPenalties",
  "executeSubmitKeeperAttestation"
] as const;
