/**
 * Dispute DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dispute DTOs
 *
 * DDD: Application DTOs for Dispute use cases.
 */

import type { ListDisputesParams, OpenDisputeRequestInput } from "@tidecove/core/participants/types";

export type ListDisputesInput = ListDisputesParams;

export type OpenDisputeInput = OpenDisputeRequestInput;

export type ListDisputesOutput = {};

export type OpenDisputeOutput = {};
