/**
 * Suspend DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Suspend DTOs
 *
 * DDD: Application DTOs for Suspend use cases.
 */

import type { SuspendParticipantParams } from "@tidecove/core/participants/types";

export type SuspendParticipantInput = SuspendParticipantParams;

export type SuspendParticipantOutput = {};
