/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @tidecove/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@tidecove/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@tidecove/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@tidecove/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@tidecove/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@tidecove/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _assets from "./assets/index.js";
import * as _compliance from "./compliance/index.js";
import * as _entitlements from "./entitlements/index.js";
import * as _identity from "./identity/index.js";
import * as _keepers from "./keepers/index.js";
import * as _licences from "./licences/index.js";
import * as _marketplace from "./marketplace/index.js";
import * as _participants from "./participants/index.js";
import * as _settlements from "./settlements/index.js";

// Export as namespaces
export const _shared = __shared;
export const assets = _assets;
export const compliance = _compliance;
export const entitlements = _entitlements;
export const identity = _identity;
export const keepers = _keepers;
export const licences = _licences;
export const marketplace = _marketplace;
export const participants = _participants;
export const settlements = _settlements;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@tidecove/core"; activity.types.*
//   - Direct exports: import * from "@tidecove/core/activity/types/index.js"
//   - Direct exports: import * from "@tidecove/core/activity/repositories/index.js"
//   - Direct exports: import * from "@tidecove/core/activity/models/index.js"
//   - Direct exports: import * from "@tidecove/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Assets Service
export { schemas as AssetsSchemas } from "./assets/schemas/assets.schemas.js";

// Compliance Service
export { schemas as ComplianceSchemas } from "./compliance/schemas/compliance.schemas.js";

// Entitlements Service
export { schemas as EntitlementsSchemas } from "./entitlements/schemas/entitlements.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Keepers Service
export { schemas as KeepersSchemas } from "./keepers/schemas/keepers.schemas.js";

// Licences Service
export { schemas as LicencesSchemas } from "./licences/schemas/licences.schemas.js";

// Marketplace Service
export { schemas as MarketplaceSchemas } from "./marketplace/schemas/marketplace.schemas.js";

// Participants Service
export { schemas as ParticipantsSchemas } from "./participants/schemas/participants.schemas.js";

// Settlements Service
export { schemas as SettlementsSchemas } from "./settlements/schemas/settlements.schemas.js";

