/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { keeperAttestationRoutes } from "./keeper-attestation.routes.js";
export { keeperPenaltyRoutes } from "./keeper-penalty.routes.js";
