/**
 * GetMarketplaceFront handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getMarketplaceFront } from "@tidecove/api-server/domains/marketplace/handlers";
import type { MarketplaceDDDDependencies } from "@tidecove/api-server/domains/marketplace";
import { createMarketplaceFront as createMarketplaceFrontEntity } from "@tidecove/factories/marketplace";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { MARKETPLACE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetMarketplaceFront", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MarketplaceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MarketplaceDDDDependencies>(
      MARKETPLACE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createMarketplaceFrontEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetMarketplaceFront, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { frontId: entity.id };

    await getMarketplaceFront(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetMarketplaceFront.execute).toHaveBeenCalledWith(expect.objectContaining({ frontId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { frontId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetMarketplaceFront, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getMarketplaceFront(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
