/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-marketplace-front.handler.test.js";
export * from "./list-marketplace-fronts.handler.test.js";
export * from "./register-marketplace-front.handler.test.js";
export * from "./update-marketplace-front.handler.test.js";
