/**
 * RegisterMarketplaceFront handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { registerMarketplaceFront } from "@tidecove/api-server/domains/marketplace/handlers";
import type { MarketplaceDDDDependencies } from "@tidecove/api-server/domains/marketplace";
import { createMarketplaceFront as createMarketplaceFrontEntity } from "@tidecove/factories/marketplace";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { MARKETPLACE_USE_CASES } from "../__factories__/use-cases.js";

describe("RegisterMarketplaceFront", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MarketplaceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MarketplaceDDDDependencies>(
      MARKETPLACE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createMarketplaceFrontEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRegisterMarketplaceFront, "execute").mockResolvedValue(useCaseResult);

    await registerMarketplaceFront(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRegisterMarketplaceFront.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
