/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Licences Domain Use Cases
 * 
 * List of all use case names for the licences domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const LICENCES_USE_CASES = [
  "executeAmendLicenceOffer",
  "executeCreateLicenceOffer",
  "executeGetLicenceOffer",
  "executeListLicenceOffers",
  "executeRevokeLicenceOffer"
] as const;
