/**
 * LicenceOfferRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LicenceOfferRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LicenceOfferRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LicenceOfferRepository,
} from "@tidecove/services/licences";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LicenceOfferRepositoryDdb } from "./licence-offer-repository.ddb.js";

/**
 * LicenceOfferRepositoryAdapter
 *
 * Implements LicenceOfferRepository port for infrastructure layer.
 */
export class LicenceOfferRepositoryAdapter implements LicenceOfferRepository {
  private readonly ddb: LicenceOfferRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LicenceOfferRepositoryDdb(this.dynamoClient);
  }

  async listLicenceOffers(input: Parameters<LicenceOfferRepository['listLicenceOffers']>[0]): Promise<Awaited<ReturnType<LicenceOfferRepository['listLicenceOffers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLicenceOffers(input);
  }

  async createLicenceOffer(input: Parameters<LicenceOfferRepository['createLicenceOffer']>[0]): Promise<Awaited<ReturnType<LicenceOfferRepository['createLicenceOffer']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createLicenceOffer(input);
  }

  async getLicenceOffer(input: Parameters<LicenceOfferRepository['getLicenceOffer']>[0]): Promise<Awaited<ReturnType<LicenceOfferRepository['getLicenceOffer']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLicenceOffer(input);
  }

  async amendLicenceOffer(input: Parameters<LicenceOfferRepository['amendLicenceOffer']>[0]): Promise<Awaited<ReturnType<LicenceOfferRepository['amendLicenceOffer']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.amendLicenceOffer(input);
  }
}
