/**
 * ExecuteListDisputes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDisputes Use Case
 *
 * DDD: Application use case for list Dispute.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDisputesInput, ListDisputesOutput } from "../dto/dispute.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { DisputeRepository } from "../ports";

export class ExecuteListDisputes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dispute: DisputeRepository
  ) {}

  async execute(input: ListDisputesInput): Promise<ListDisputesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dispute.listDisputes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDisputesOutput;
  }
}
