/**
 * Keepers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Keepers Domain Module - Composition root
 *
 * DDD: Composition root for keepers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  KeeperAttestationRepositoryAdapter,
  KeeperPenaltyRepositoryAdapter,
} from "@tidecove/adapters/keepers";
import { getIdGeneratorService } from "@tidecove/adapters";
import type { AdapterDynamoDBClient } from "@tidecove/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateKeeperPenalty,
  ExecuteListKeeperAttestations,
  ExecuteListKeeperPenalties,
  ExecuteSubmitKeeperAttestation,
} from "@tidecove/services/keepers/usecases";
// Ports (interfaces)
import type {
  KeeperAttestationRepository,
  KeeperPenaltyRepository,
} from "@tidecove/services/keepers/ports";

export interface KeepersDomainModule {
  repos: {
    keeperAttestations: KeeperAttestationRepository;
    keeperPenalties: KeeperPenaltyRepository;
  };
  useCases: {
    keeperAttestations: {
      create: ExecuteSubmitKeeperAttestation;
      list: ExecuteListKeeperAttestations;
    };
    keeperPenalties: {
      create: ExecuteCreateKeeperPenalty;
      list: ExecuteListKeeperPenalties;
    };
  };
}

export function buildKeepersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): KeepersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      keeperAttestations?: KeeperAttestationRepository;
      keeperPenalties?: KeeperPenaltyRepository;
    } = {};

    obj.keeperAttestations = new KeeperAttestationRepositoryAdapter(dynamoClient);
    obj.keeperPenalties = new KeeperPenaltyRepositoryAdapter(dynamoClient);
    return {
      keeperAttestations: obj.keeperAttestations!,
      keeperPenalties: obj.keeperPenalties!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    keeperAttestations: {
      create: new ExecuteSubmitKeeperAttestation(executionContext, idGenerator, repos.keeperAttestations),
      list: new ExecuteListKeeperAttestations(executionContext, idGenerator, repos.keeperAttestations),
    },
    keeperPenalties: {
      create: new ExecuteCreateKeeperPenalty(executionContext, idGenerator, repos.keeperPenalties),
      list: new ExecuteListKeeperPenalties(executionContext, idGenerator, repos.keeperPenalties),
    },
  };
  return { repos, useCases: useCases as KeepersDomainModule["useCases"] };
}
