/**
 * ExecuteGetAsset - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAsset Use Case
 *
 * DDD: Application use case for get Asset.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAssetInput, GetAssetOutput } from "../dto/asset.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { AssetRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAsset {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly asset: AssetRepository
  ) {}

  async execute(input: GetAssetInput): Promise<GetAssetOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.astId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).assetId) {
      throw new ValidationError("assetId is required");
    }
    const assetId = (input as any).assetId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.asset.getAsset({ assetId: assetId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${assetId}`);
    }

    return entity as GetAssetOutput;
  }
}
