/**
 * ExecuteListAssets - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAssets Use Case
 *
 * DDD: Application use case for list Asset.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAssetsInput, ListAssetsOutput } from "../dto/asset.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { AssetRepository } from "../ports";

export class ExecuteListAssets {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly asset: AssetRepository
  ) {}

  async execute(input: ListAssetsInput): Promise<ListAssetsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.astId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.asset.listAssets({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAssetsOutput;
  }
}
