/**
 * MarketplaceFront Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MarketplaceFrontEntity } from "@tidecove/core/marketplace/models/index.js";
import { marketplaceSchemas } from "@tidecove/core/marketplace";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mkt";

export function createMarketplaceFront(overrides: Partial<MarketplaceFrontEntity> = {}) {
  const raw = {
    id: overrides.id ?? `mkt_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "active",
    takeRateBps: overrides.takeRateBps ?? faker.number.int(),
    ...overrides,
  };

  return marketplaceSchemas.MarketplaceFront.parse(raw);
}

export function marketplaceFrontBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMarketplaceFront(overrides));
}
