/**
 * LicenceOfferRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LicenceOfferRepository Port
 *
 * DDD: Application port for licenceofferrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AmendLicenceOfferInput, AmendLicenceOfferOutput, CreateLicenceOfferInput, CreateLicenceOfferOutput, GetLicenceOfferInput, GetLicenceOfferOutput, ListLicenceOffersInput, ListLicenceOffersOutput } from "../dto/licence-offer.dto";
export interface LicenceOfferRepository {
  listLicenceOffers(input: ListLicenceOffersInput): Promise<ListLicenceOffersOutput>;
  createLicenceOffer(input: CreateLicenceOfferInput): Promise<CreateLicenceOfferOutput>;
  getLicenceOffer(input: GetLicenceOfferInput): Promise<GetLicenceOfferOutput>;
  amendLicenceOffer(input: AmendLicenceOfferInput): Promise<AmendLicenceOfferOutput>;
}

export type { AmendLicenceOfferInput, AmendLicenceOfferOutput, CreateLicenceOfferInput, CreateLicenceOfferOutput, GetLicenceOfferInput, GetLicenceOfferOutput, ListLicenceOffersInput, ListLicenceOffersOutput } from "../dto/licence-offer.dto";
