/**
 * ExecuteAmendLicenceOffer - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAmendLicenceOffer Use Case
 *
 * DDD: Application use case for get LicenceOffer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AmendLicenceOfferInput, AmendLicenceOfferOutput } from "../dto/licence-offer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { LicenceOfferRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAmendLicenceOffer {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly licenceOffer: LicenceOfferRepository
  ) {}

  async execute(input: AmendLicenceOfferInput): Promise<AmendLicenceOfferOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.licId();

    // All field names extracted from OpenAPI spec: grandfatherActiveEntitlements, lawfulBasis, marketplaceFrontIds, priceAmount, purposeTags, revokeSlaHours
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).offerId) {
      throw new ValidationError("offerId is required");
    }
    const offerId = (input as any).offerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.licenceOffer.amendLicenceOffer({ offerId: offerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${offerId}`);
    }

    return entity as AmendLicenceOfferOutput;
  }
}
