/**
 * ExecuteListLicenceOffers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLicenceOffers Use Case
 *
 * DDD: Application use case for list LicenceOffer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLicenceOffersInput, ListLicenceOffersOutput } from "../dto/licence-offer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { LicenceOfferRepository } from "../ports";

export class ExecuteListLicenceOffers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly licenceOffer: LicenceOfferRepository
  ) {}

  async execute(input: ListLicenceOffersInput): Promise<ListLicenceOffersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.licId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.licenceOffer.listLicenceOffers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLicenceOffersOutput;
  }
}
