/**
 * ExecuteCreateLicenceOffer - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateLicenceOffer Use Case
 *
 * DDD: Application use case for create LicenceOffer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateLicenceOfferInput, CreateLicenceOfferOutput } from "../dto/licence-offer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { LicenceOfferRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateLicenceOffer {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly licenceOffer: LicenceOfferRepository
  ) {}

  async execute(input: CreateLicenceOfferInput): Promise<CreateLicenceOfferOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.licId();

    // All field names extracted from OpenAPI spec: assetId, currency, grandfatherActiveEntitlements, lawfulBasis, licenceClass, marketplaceFrontIds, priceAmount, purposeTags, revokeSlaHours
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.assetId) {
      throw new ValidationError("assetId is required");
    }
    if (!input.currency) {
      throw new ValidationError("currency is required");
    }
    if (!input.licenceClass) {
      throw new ValidationError("licenceClass is required");
    }
    if (!input.priceAmount) {
      throw new ValidationError("priceAmount is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (licences domain)
    const entityId = this.idGenerator.licId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.licenceOffer.createLicenceOffer({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateLicenceOfferOutput;
  }
}
