/**
 * CreateComplianceTag handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createComplianceTag } from "@tidecove/api-server/domains/compliance/handlers";
import type { ComplianceDDDDependencies } from "@tidecove/api-server/domains/compliance";
import { createComplianceTag as createComplianceTagEntity } from "@tidecove/factories/compliance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { COMPLIANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateComplianceTag", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ComplianceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ComplianceDDDDependencies>(
      COMPLIANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createComplianceTagEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateComplianceTag, "execute").mockResolvedValue(useCaseResult);

    await createComplianceTag(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateComplianceTag.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
