/**
 * GetComplianceTag handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getComplianceTag } from "@tidecove/api-server/domains/compliance/handlers";
import type { ComplianceDDDDependencies } from "@tidecove/api-server/domains/compliance";
import { createComplianceTag as createComplianceTagEntity } from "@tidecove/factories/compliance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { COMPLIANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetComplianceTag", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ComplianceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ComplianceDDDDependencies>(
      COMPLIANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createComplianceTagEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetComplianceTag, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { tagId: entity.id };

    await getComplianceTag(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetComplianceTag.execute).toHaveBeenCalledWith(expect.objectContaining({ tagId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { tagId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetComplianceTag, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getComplianceTag(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
