/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-compliance-tag.handler.test.js";
export * from "./get-compliance-tag.handler.test.js";
export * from "./list-compliance-tags.handler.test.js";
export * from "./update-compliance-tag.handler.test.js";
