/**
 * ComplianceTag Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ComplianceTagEntity } from "@tidecove/core/compliance/models/index.js";
import { complianceSchemas } from "@tidecove/core/compliance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cmp";

export function createComplianceTag(overrides: Partial<ComplianceTagEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cmp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    assetId: overrides.assetId ?? faker.string.uuid(),
    lawfulBasis: overrides.lawfulBasis ?? faker.lorem.word(),
    purposeTags: overrides.purposeTags ?? [],
    ...overrides,
  };

  return complianceSchemas.ComplianceTag.parse(raw);
}

export function complianceTagBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createComplianceTag(overrides));
}
