/**
 * LicenceOffer Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/licences.openapi.types.js";
import { schemas } from "../schemas/licences.schemas.js";

/**
 * Entity: LicenceOfferEntity
 * Description: Represents the LicenceOffer domain model.
 * Source: schemas.LicenceOffer
 * Type: Persisted Entity (x-dynamodb)
 */
export const LicenceOfferEntitySchema = schemas.LicenceOffer;
export type LicenceOfferEntity = components["schemas"]["LicenceOffer"];
