/**
 * CreateRevoke DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RevokeLicenceOfferParams } from "@tidecove/core/licences";

export function createCreateRevokeRequest(overrides: Partial<RevokeLicenceOfferParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
