/**
 * KeeperAttestation Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/keepers.openapi.types.js";
import { schemas } from "../schemas/keepers.schemas.js";

/**
 * Entity: KeeperAttestationEntity
 * Description: Represents the KeeperAttestation domain model.
 * Source: schemas.KeeperAttestation
 * Type: Persisted Entity (x-dynamodb)
 */
export const KeeperAttestationEntitySchema = schemas.KeeperAttestation;
export type KeeperAttestationEntity = components["schemas"]["KeeperAttestation"];
