/**
 * KeeperPenalty Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/keepers.openapi.types.js";
import { schemas } from "../schemas/keepers.schemas.js";

/**
 * Entity: KeeperPenaltyEntity
 * Description: Represents the KeeperPenalty domain model.
 * Source: schemas.KeeperPenalty
 * Type: Persisted Entity (x-dynamodb)
 */
export const KeeperPenaltyEntitySchema = schemas.KeeperPenalty;
export type KeeperPenaltyEntity = components["schemas"]["KeeperPenalty"];
