/**
 * KeeperPenalty DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KeeperPenalty DTOs
 *
 * DDD: Application DTOs for KeeperPenalty use cases.
 */

import type { CreateKeeperPenaltyRequestInput, ListKeeperPenaltiesParams } from "@tidecove/core/keepers/types";

export type ListKeeperPenaltiesInput = ListKeeperPenaltiesParams;

export type CreateKeeperPenaltyInput = CreateKeeperPenaltyRequestInput;

export type ListKeeperPenaltiesOutput = {};

export type CreateKeeperPenaltyOutput = {};
