/**
 * ExecuteListKeeperPenalties - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListKeeperPenalties Use Case
 *
 * DDD: Application use case for list KeeperPenalty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListKeeperPenaltiesInput, ListKeeperPenaltiesOutput } from "../dto/keeper-penalty.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { KeeperPenaltyRepository } from "../ports";

export class ExecuteListKeeperPenalties {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly keeperPenalty: KeeperPenaltyRepository
  ) {}

  async execute(input: ListKeeperPenaltiesInput): Promise<ListKeeperPenaltiesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.kprId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.keeperPenalty.listKeeperPenalties({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListKeeperPenaltiesOutput;
  }
}
