/**
 * ExecuteListKeeperAttestations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListKeeperAttestations Use Case
 *
 * DDD: Application use case for list KeeperAttestation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListKeeperAttestationsInput, ListKeeperAttestationsOutput } from "../dto/keeper-attestation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { KeeperAttestationRepository } from "../ports";

export class ExecuteListKeeperAttestations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly keeperAttestation: KeeperAttestationRepository
  ) {}

  async execute(input: ListKeeperAttestationsInput): Promise<ListKeeperAttestationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.kprId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.keeperAttestation.listKeeperAttestations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListKeeperAttestationsOutput;
  }
}
