/**
 * Handlers for Evaluate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ComplianceDomainModule } from "../dependencies/compliance-ddd.dependencies.js";
import type { EvaluatePurposeGateInput } from "@tidecove/services/compliance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/purpose-gate/evaluate
 * Operation: evaluatePurposeGate
 */
export async function evaluatePurposeGate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ComplianceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: EvaluatePurposeGateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.evaluates.create.execute(input);
  return reply.code(200).send(result);
}


