/**
 * Suspend Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SuspendEntity } from "@tidecove/core/participants/models/index.js";
import { participantsSchemas } from "@tidecove/core/participants";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ptc";

export function createSuspend(overrides: Partial<SuspendEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ptc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    displayName: overrides.displayName ?? faker.person.fullName(),
    role: overrides.role ?? "seller",
    status: overrides.status ?? "active",
    vettingStatus: overrides.vettingStatus ?? "unvetted",
    ...overrides,
  };

  return participantsSchemas.Participant.parse(raw);
}

export function suspendBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSuspend(overrides));
}
