/**
 * ListMarketplaceFront DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListMarketplaceFrontsParams } from "@tidecove/core/marketplace";

export function createListMarketplaceFrontRequest(overrides: Partial<ListMarketplaceFrontsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
