/**
 * Routes for ComputeJob
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { cancelComputeJob, getComputeJob, listComputeJobs, scheduleComputeJob } from "../handlers/compute-job.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function computeJobRoutes(fastify: FastifyInstance) {
  // GET /v1/compute-jobs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/compute-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEntitlementsDependenciesForRequest();
        await listComputeJobs(request, reply, deps);
      });
    }
  );


  // POST /v1/compute-jobs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/compute-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEntitlementsDependenciesForRequest();
        await scheduleComputeJob(request, reply, deps);
      });
    }
  );


  // POST /v1/compute-jobs/{jobId} (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/compute-jobs/:jobId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEntitlementsDependenciesForRequest();
        await cancelComputeJob(request, reply, deps);
      });
    }
  );


  // GET /v1/compute-jobs/{jobId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/compute-jobs/:jobId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEntitlementsDependenciesForRequest();
        await getComputeJob(request, reply, deps);
      });
    }
  );


}
