/**
 * Routes for Entitlement
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getEntitlement, listEntitlements, purchaseEntitlement } from "../handlers/entitlement.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function entitlementRoutes(fastify: FastifyInstance) {
  // GET /v1/entitlements (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/entitlements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEntitlementsDependenciesForRequest();
        await listEntitlements(request, reply, deps);
      });
    }
  );


  // POST /v1/entitlements (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/entitlements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEntitlementsDependenciesForRequest();
        await purchaseEntitlement(request, reply, deps);
      });
    }
  );


  // GET /v1/entitlements/{entitlementId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/entitlements/:entitlementId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { entitlementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEntitlementsDependenciesForRequest();
        await getEntitlement(request, reply, deps);
      });
    }
  );


}
