/**
 * ExecuteRegisterMarketplaceFront - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterMarketplaceFront Use Case
 *
 * DDD: Application use case for create MarketplaceFront.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterMarketplaceFrontInput, RegisterMarketplaceFrontOutput } from "../dto/marketplace-front.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { MarketplaceFrontRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterMarketplaceFront {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly marketplaceFront: MarketplaceFrontRepository
  ) {}

  async execute(input: RegisterMarketplaceFrontInput): Promise<RegisterMarketplaceFrontOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mktId();

    // All field names extracted from OpenAPI spec: fiatOnRampEnabled, indexedOfferIds, name, takeRateBps, vertical
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.takeRateBps) {
      throw new ValidationError("takeRateBps is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (marketplace domain)
    const entityId = this.idGenerator.mktId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.marketplaceFront.registerMarketplaceFront({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterMarketplaceFrontOutput;
  }
}
