/**
 * ExecuteGetMarketplaceFront - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetMarketplaceFront Use Case
 *
 * DDD: Application use case for get MarketplaceFront.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetMarketplaceFrontInput, GetMarketplaceFrontOutput } from "../dto/marketplace-front.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { MarketplaceFrontRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetMarketplaceFront {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly marketplaceFront: MarketplaceFrontRepository
  ) {}

  async execute(input: GetMarketplaceFrontInput): Promise<GetMarketplaceFrontOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mktId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).frontId) {
      throw new ValidationError("frontId is required");
    }
    const frontId = (input as any).frontId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.marketplaceFront.getMarketplaceFront({ frontId: frontId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${frontId}`);
    }

    return entity as GetMarketplaceFrontOutput;
  }
}
