/**
 * GetSettlement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetSettlementStatementParams } from "@tidecove/core/settlements";

export function createGetSettlementRequest(overrides: Partial<GetSettlementStatementParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
