/**
 * Handlers for AccessCredential
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EntitlementsDomainModule } from "../dependencies/entitlements-ddd.dependencies.js";
import type { GetAccessCredentialInput } from "@tidecove/services/entitlements";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/access-credentials/{credentialId}
 * Operation: getAccessCredential
 */
export async function getAccessCredential(
  request: FastifyRequest<{ Params: { credentialId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EntitlementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAccessCredentialInput = {
    credentialId: request.params.credentialId,
  };
  const result = await deps.useCases.accessCredentials.get.execute(input);
  return reply.code(200).send(result);
}


