/**
 * Handlers for Entitlement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EntitlementsDomainModule } from "../dependencies/entitlements-ddd.dependencies.js";
import type { GetEntitlementInput, ListEntitlementsInput, PurchaseEntitlementInput } from "@tidecove/services/entitlements";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/entitlements
 * Operation: listEntitlements
 */
export async function listEntitlements(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], buyerParticipantId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EntitlementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEntitlementsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.entitlements.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/entitlements
 * Operation: purchaseEntitlement
 */
export async function purchaseEntitlement(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EntitlementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PurchaseEntitlementInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.entitlements.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/entitlements/{entitlementId}
 * Operation: getEntitlement
 */
export async function getEntitlement(
  request: FastifyRequest<{ Params: { entitlementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EntitlementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEntitlementInput = {
    entitlementId: request.params.entitlementId,
  };
  const result = await deps.useCases.entitlements.get.execute(input);
  return reply.code(200).send(result);
}


