/**
 * GetLicenceOffer handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getLicenceOffer } from "@tidecove/api-server/domains/licences/handlers";
import type { LicencesDDDDependencies } from "@tidecove/api-server/domains/licences";
import { createLicenceOffer as createLicenceOfferEntity } from "@tidecove/factories/licences";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { LICENCES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetLicenceOffer", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LicencesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LicencesDDDDependencies>(
      LICENCES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createLicenceOfferEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetLicenceOffer, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { offerId: entity.id };

    await getLicenceOffer(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetLicenceOffer.execute).toHaveBeenCalledWith(expect.objectContaining({ offerId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { offerId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetLicenceOffer, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getLicenceOffer(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
