/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./amend-licence-offer.handler.test.js";
export * from "./create-licence-offer.handler.test.js";
export * from "./get-licence-offer.handler.test.js";
export * from "./list-licence-offers.handler.test.js";
