/**
 * ListLicenceOffers handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listLicenceOffers } from "@tidecove/api-server/domains/licences/handlers";
import type { LicencesDDDDependencies } from "@tidecove/api-server/domains/licences";
import { createLicenceOffer as createLicenceOfferEntity } from "@tidecove/factories/licences";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { LICENCES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListLicenceOffers", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LicencesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LicencesDDDDependencies>(
      LICENCES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createLicenceOfferEntity({ orgId }),
      createLicenceOfferEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListLicenceOffers, "execute").mockResolvedValue(useCaseResult);

    await listLicenceOffers(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListLicenceOffers.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
