/**
 * SettlementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SettlementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SettlementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SettlementRepository,
} from "@tidecove/services/settlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SettlementRepositoryDdb } from "./settlement-repository.ddb.js";

/**
 * SettlementRepositoryAdapter
 *
 * Implements SettlementRepository port for infrastructure layer.
 */
export class SettlementRepositoryAdapter implements SettlementRepository {
  private readonly ddb: SettlementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SettlementRepositoryDdb(this.dynamoClient);
  }

  async listSettlementStatements(input: Parameters<SettlementRepository['listSettlementStatements']>[0]): Promise<Awaited<ReturnType<SettlementRepository['listSettlementStatements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSettlementStatements(input);
  }

  async generateSettlementStatement(input: Parameters<SettlementRepository['generateSettlementStatement']>[0]): Promise<Awaited<ReturnType<SettlementRepository['generateSettlementStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.generateSettlementStatement(input);
  }

  async getSettlementStatement(input: Parameters<SettlementRepository['getSettlementStatement']>[0]): Promise<Awaited<ReturnType<SettlementRepository['getSettlementStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSettlementStatement(input);
  }
}
