/**
 * AssetRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssetRepository Port
 *
 * DDD: Application port for assetrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type {
  GetAssetInput,
  GetAssetOutput,
  ListAssetsInput,
  ListAssetsOutput,
  PublishAssetInput,
  PublishAssetOutput,
  UpdateAssetInput,
  UpdateAssetOutput,
} from "../dto/asset.dto";
export interface AssetRepository {
  listAssets(input: ListAssetsInput): Promise<ListAssetsOutput>;
  getAsset(input: GetAssetInput): Promise<GetAssetOutput>;
  updateAsset(input: UpdateAssetInput): Promise<UpdateAssetOutput>;
  /** Persist a newly published/drafted asset (create). */
  publishAsset(input: PublishAssetInput & Record<string, unknown>): Promise<PublishAssetOutput>;
}

export type {
  GetAssetInput,
  GetAssetOutput,
  ListAssetsInput,
  ListAssetsOutput,
  PublishAssetInput,
  PublishAssetOutput,
  UpdateAssetInput,
  UpdateAssetOutput,
} from "../dto/asset.dto";
