/**
 * Repository interface for LicenceOffer
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LicenceOfferEntity
} from "../models/licence-offer.entity.js";
import type {
  ListLicenceOffersParams,
  LicenceOffer,
  AmendLicenceOfferRequestInput
} from "../types/index.js";
/**
 * LicenceOfferRepository Interface
 */
export interface LicenceOfferRepository extends CreateUpdateReadRepository<LicenceOfferEntity, LicenceOffer, AmendLicenceOfferRequestInput, string, ListLicenceOffersParams> {

}
