/**
 * Repository interface for Revoke
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RevokeEntity
} from "../models/revoke.entity.js";
import type {
  LicenceOffer
} from "../types/index.js";
/**
 * RevokeRepository Interface
 */
export interface RevokeRepository extends CreateReadRepository<RevokeEntity, LicenceOffer, string, Record<string, never>> {

}
