/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@tidecove/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@tidecove/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@tidecove/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _assets from "./assets/index.js";
import * as _compliance from "./compliance/index.js";
import * as _entitlements from "./entitlements/index.js";
import * as _identity from "./identity/index.js";
import * as _keepers from "./keepers/index.js";
import * as _licences from "./licences/index.js";
import * as _marketplace from "./marketplace/index.js";
import * as _participants from "./participants/index.js";
import * as _settlements from "./settlements/index.js";

// Export as namespaces
export const assets = _assets;
export const compliance = _compliance;
export const entitlements = _entitlements;
export const identity = _identity;
export const keepers = _keepers;
export const licences = _licences;
export const marketplace = _marketplace;
export const participants = _participants;
export const settlements = _settlements;
