/**
 * ListKeeperAttestations handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listKeeperAttestations } from "@tidecove/api-server/domains/keepers/handlers";
import type { KeepersDDDDependencies } from "@tidecove/api-server/domains/keepers";
import { createKeeperAttestation as createKeeperAttestationEntity } from "@tidecove/factories/keepers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { KEEPERS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListKeeperAttestations", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: KeepersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<KeepersDDDDependencies>(
      KEEPERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createKeeperAttestationEntity({ orgId }),
      createKeeperAttestationEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListKeeperAttestations, "execute").mockResolvedValue(useCaseResult);

    await listKeeperAttestations(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListKeeperAttestations.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
