/**
 * LicenceOffer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LicenceOffer DTOs
 *
 * DDD: Application DTOs for LicenceOffer use cases.
 */

import type { AmendLicenceOfferParams, AmendLicenceOfferRequestInput, CreateLicenceOfferRequestInput, GetLicenceOfferParams, ListLicenceOffersParams } from "@tidecove/core/licences/types";

export type ListLicenceOffersInput = ListLicenceOffersParams;

export type CreateLicenceOfferInput = CreateLicenceOfferRequestInput;

export type GetLicenceOfferInput = GetLicenceOfferParams;

export type AmendLicenceOfferInput = AmendLicenceOfferParams & AmendLicenceOfferRequestInput;

export type ListLicenceOffersOutput = {};

export type CreateLicenceOfferOutput = {};

export type GetLicenceOfferOutput = {};

export type AmendLicenceOfferOutput = {};
