/**
 * Assets DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assets Domain Module - Composition root
 *
 * DDD: Composition root for assets domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssetRepositoryAdapter,
} from "@tidecove/adapters/assets";
import { getIdGeneratorService } from "@tidecove/adapters";
import type { AdapterDynamoDBClient } from "@tidecove/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetAsset,
  ExecuteListAssets,
  ExecutePublishAsset,
  ExecuteUpdateAsset,
} from "@tidecove/services/assets/usecases";
// Ports (interfaces)
import type {
  AssetRepository,
} from "@tidecove/services/assets/ports";

export interface AssetsDomainModule {
  repos: {
    assets: AssetRepository;
  };
  useCases: {
    assets: {
      get: ExecuteGetAsset;
      list: ExecuteListAssets;
      publish: ExecutePublishAsset;
      update: ExecuteUpdateAsset;
    };
  };
}

export function buildAssetsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssetsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assets?: AssetRepository;
    } = {};

    obj.assets = new AssetRepositoryAdapter(dynamoClient);
    return {
      assets: obj.assets!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assets: {
      get: new ExecuteGetAsset(executionContext, idGenerator, repos.assets),
      list: new ExecuteListAssets(executionContext, idGenerator, repos.assets),
      publish: new ExecutePublishAsset(executionContext, idGenerator, repos.assets),
      update: new ExecuteUpdateAsset(executionContext, idGenerator, repos.assets),
    },
  };
  return { repos, useCases: useCases as AssetsDomainModule["useCases"] };
}
