/**
 * RevokeLicenceOffer handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { revokeLicenceOffer } from "@tidecove/api-server/domains/licences/handlers";
import type { LicencesDDDDependencies } from "@tidecove/api-server/domains/licences";
import { createRevoke as createRevokeEntity } from "@tidecove/factories/licences";
import { createCreateRevokeRequest } from "@tidecove/factories/licences";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { LICENCES_USE_CASES } from "../__factories__/use-cases.js";

describe("RevokeLicenceOffer", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LicencesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LicencesDDDDependencies>(
      LICENCES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateRevokeRequest();
    const entity = createRevokeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRevokeLicenceOffer, "execute").mockResolvedValue(useCaseResult);

    await revokeLicenceOffer(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRevokeLicenceOffer.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
