/**
 * ExecutePurchaseEntitlement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePurchaseEntitlement Use Case
 *
 * DDD: Application use case for get Entitlement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PurchaseEntitlementInput, PurchaseEntitlementOutput } from "../dto/entitlement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { EntitlementRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePurchaseEntitlement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly entitlement: EntitlementRepository
  ) {}

  async execute(input: PurchaseEntitlementInput): Promise<PurchaseEntitlementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.entId();

    // All field names extracted from OpenAPI spec: buyerParticipantId, declaredPurpose, marketplaceFrontId, offerId, validUntil
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).buyerParticipantId) {
      throw new ValidationError("buyerParticipantId is required");
    }
    const buyerparticipantId = (input as any).buyerParticipantId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.entitlement.purchaseEntitlement({ buyerParticipantId: buyerparticipantId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${buyerparticipantId}`);
    }

    return entity as PurchaseEntitlementOutput;
  }
}
