/**
 * ExecuteScheduleComputeJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteScheduleComputeJob Use Case
 *
 * DDD: Application use case for get ComputeJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ScheduleComputeJobInput, ScheduleComputeJobOutput } from "../dto/compute-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { ComputeJobRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteScheduleComputeJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly computeJob: ComputeJobRepository
  ) {}

  async execute(input: ScheduleComputeJobInput): Promise<ScheduleComputeJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.entId();

    // All field names extracted from OpenAPI spec: entitlementId, sellerEndpoint
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).entitlementId) {
      throw new ValidationError("entitlementId is required");
    }
    const entitlementId = (input as any).entitlementId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.computeJob.scheduleComputeJob({ entitlementId: entitlementId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${entitlementId}`);
    }

    return entity as ScheduleComputeJobOutput;
  }
}
