/**
 * ExecuteGetComputeJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetComputeJob Use Case
 *
 * DDD: Application use case for get ComputeJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetComputeJobInput, GetComputeJobOutput } from "../dto/compute-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { ComputeJobRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetComputeJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly computeJob: ComputeJobRepository
  ) {}

  async execute(input: GetComputeJobInput): Promise<GetComputeJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.entId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).jobId) {
      throw new ValidationError("jobId is required");
    }
    const jobId = (input as any).jobId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.computeJob.getComputeJob({ jobId: jobId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${jobId}`);
    }

    return entity as GetComputeJobOutput;
  }
}
