/**
 * ExecuteListEntitlements - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEntitlements Use Case
 *
 * DDD: Application use case for list Entitlement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEntitlementsInput, ListEntitlementsOutput } from "../dto/entitlement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { EntitlementRepository } from "../ports";

export class ExecuteListEntitlements {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly entitlement: EntitlementRepository
  ) {}

  async execute(input: ListEntitlementsInput): Promise<ListEntitlementsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.entId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.entitlement.listEntitlements({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEntitlementsOutput;
  }
}
