/**
 * ExecuteListComputeJobs - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListComputeJobs Use Case
 *
 * DDD: Application use case for list ComputeJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListComputeJobsInput, ListComputeJobsOutput } from "../dto/compute-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { ComputeJobRepository } from "../ports";

export class ExecuteListComputeJobs {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly computeJob: ComputeJobRepository
  ) {}

  async execute(input: ListComputeJobsInput): Promise<ListComputeJobsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.entId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.computeJob.listComputeJobs({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListComputeJobsOutput;
  }
}
