/**
 * ExecuteCancelComputeJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCancelComputeJob Use Case
 *
 * DDD: Application use case for update ComputeJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CancelComputeJobInput, CancelComputeJobOutput } from "../dto/compute-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tidecove/services/_shared/index.js";
import type { ComputeJobRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteCancelComputeJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly computeJob: ComputeJobRepository
  ) {}

  async execute(input: CancelComputeJobInput): Promise<CancelComputeJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.entId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).id) {
      throw new ValidationError("id is required");
    }
    const idValue = (input as any).id;

    // Load existing entity
    const existing = await this.computeJob.scheduleComputeJob({ id: idValue, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${idValue}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.computeJob.cancelComputeJob({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as CancelComputeJobOutput;
  }
}
