/**
 * Decision Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/compliance.openapi.types.js";
import { schemas } from "../schemas/compliance.schemas.js";

/**
 * Entity: DecisionEntity
 * Description: Represents the Decision domain model.
 * Source: schemas.PurposeGateDecision
 * Type: Persisted Entity (x-dynamodb)
 */
export const DecisionEntitySchema = schemas.PurposeGateDecision;
export type DecisionEntity = components["schemas"]["PurposeGateDecision"];
