/**
 * Handlers for LicenceOffer
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LicencesDomainModule } from "../dependencies/licences-ddd.dependencies.js";
import type { AmendLicenceOfferInput, CreateLicenceOfferInput, GetLicenceOfferInput, ListLicenceOffersInput } from "@tidecove/services/licences";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/licence-offers
 * Operation: listLicenceOffers
 */
export async function listLicenceOffers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], assetId?: string | string[], licenceClass?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: LicencesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLicenceOffersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.licenceOffers.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/licence-offers
 * Operation: createLicenceOffer
 */
export async function createLicenceOffer(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: LicencesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateLicenceOfferInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.licenceOffers.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/licence-offers/{offerId}
 * Operation: getLicenceOffer
 */
export async function getLicenceOffer(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LicencesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLicenceOfferInput = {
    offerId: request.params.offerId,
  };
  const result = await deps.useCases.licenceOffers.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/licence-offers/{offerId}
 * Operation: amendLicenceOffer
 */
export async function amendLicenceOffer(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LicencesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AmendLicenceOfferInput = {
    offerId: request.params.offerId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.licenceOffers.get.execute(input);
  return reply.code(200).send(result);
}


