/**
 * Handlers for Revoke
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licences
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LicencesDomainModule } from "../dependencies/licences-ddd.dependencies.js";
import type { RevokeLicenceOfferInput } from "@tidecove/services/licences";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/licence-offers/{offerId}/revoke
 * Operation: revokeLicenceOffer
 */
export async function revokeLicenceOffer(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LicencesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RevokeLicenceOfferInput = {
    offerId: request.params.offerId,
  };
  const result = await deps.useCases.revokes.get.execute(input);
  return reply.code(200).send(result);
}


