/**
 * Settlement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Settlement DTOs
 *
 * DDD: Application DTOs for Settlement use cases.
 */

import type { GenerateSettlementStatementRequestInput, GetSettlementStatementParams, ListSettlementStatementsParams } from "@tidecove/core/settlements/types";

export type ListSettlementStatementsInput = ListSettlementStatementsParams;

export type GenerateSettlementStatementInput = GenerateSettlementStatementRequestInput;

export type GetSettlementStatementInput = GetSettlementStatementParams;

export type ListSettlementStatementsOutput = {};

export type GenerateSettlementStatementOutput = {};

export type GetSettlementStatementOutput = {};
