/**
 * ComplianceTagRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplianceTagRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ComplianceTagRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ComplianceTagRepository,
} from "@tidecove/services/compliance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ComplianceTagRepositoryDdb } from "./compliance-tag-repository.ddb.js";

/**
 * ComplianceTagRepositoryAdapter
 *
 * Implements ComplianceTagRepository port for infrastructure layer.
 */
export class ComplianceTagRepositoryAdapter implements ComplianceTagRepository {
  private readonly ddb: ComplianceTagRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ComplianceTagRepositoryDdb(this.dynamoClient);
  }

  async listComplianceTags(input: Parameters<ComplianceTagRepository['listComplianceTags']>[0]): Promise<Awaited<ReturnType<ComplianceTagRepository['listComplianceTags']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listComplianceTags(input);
  }

  async createComplianceTag(input: Parameters<ComplianceTagRepository['createComplianceTag']>[0]): Promise<Awaited<ReturnType<ComplianceTagRepository['createComplianceTag']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createComplianceTag(input);
  }

  async getComplianceTag(input: Parameters<ComplianceTagRepository['getComplianceTag']>[0]): Promise<Awaited<ReturnType<ComplianceTagRepository['getComplianceTag']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getComplianceTag(input);
  }

  async updateComplianceTag(input: Parameters<ComplianceTagRepository['updateComplianceTag']>[0]): Promise<Awaited<ReturnType<ComplianceTagRepository['updateComplianceTag']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateComplianceTag(input);
  }
}
