/**
 * EvaluateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvaluateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EvaluateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EvaluateRepository,
} from "@tidecove/services/compliance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EvaluateRepositoryDdb } from "./evaluate-repository.ddb.js";

/**
 * EvaluateRepositoryAdapter
 *
 * Implements EvaluateRepository port for infrastructure layer.
 */
export class EvaluateRepositoryAdapter implements EvaluateRepository {
  private readonly ddb: EvaluateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EvaluateRepositoryDdb(this.dynamoClient);
  }

  async evaluatePurposeGate(input: Parameters<EvaluateRepository['evaluatePurposeGate']>[0]): Promise<Awaited<ReturnType<EvaluateRepository['evaluatePurposeGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.evaluatePurposeGate(input);
  }
}
