/**
 * Repository interface for ComplianceTag
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ComplianceTagEntity
} from "../models/compliance-tag.entity.js";
import type {
  ListComplianceTagsParams,
  ComplianceTag,
  UpdateComplianceTagRequestInput
} from "../types/index.js";
/**
 * ComplianceTagRepository Interface
 */
export interface ComplianceTagRepository extends CreateUpdateReadRepository<ComplianceTagEntity, ComplianceTag, UpdateComplianceTagRequestInput, string, ListComplianceTagsParams> {

}
