/**
 * KeeperPenalty Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { KeeperPenaltyEntity } from "@tidecove/core/keepers/models/index.js";
import { keepersSchemas } from "@tidecove/core/keepers";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "kpr";

export function createKeeperPenalty(overrides: Partial<KeeperPenaltyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `kpp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    amount: overrides.amount ?? faker.number.int(),
    attestationId: overrides.attestationId ?? faker.string.uuid(),
    currency: overrides.currency ?? faker.lorem.word(),
    keeperParticipantId: overrides.keeperParticipantId ?? faker.string.uuid(),
    status: overrides.status ?? "open",
    ...overrides,
  };

  return keepersSchemas.KeeperPenalty.parse(raw);
}

export function keeperPenaltyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createKeeperPenalty(overrides));
}
