/**
 * Participants DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Participants Domain Module - Composition root
 *
 * DDD: Composition root for participants domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisputeRepositoryAdapter,
  ParticipantRepositoryAdapter,
  ResolveRepositoryAdapter,
  SuspendRepositoryAdapter,
} from "@tidecove/adapters/participants";
import { getIdGeneratorService } from "@tidecove/adapters";
import type { AdapterDynamoDBClient } from "@tidecove/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetParticipant,
  ExecuteListDisputes,
  ExecuteListParticipants,
  ExecuteOpenDispute,
  ExecuteRegisterParticipant,
  ExecuteResolveDispute,
  ExecuteSuspendParticipant,
  ExecuteUpdateParticipant,
} from "@tidecove/services/participants/usecases";
// Ports (interfaces)
import type {
  DisputeRepository,
  ParticipantRepository,
  ResolveRepository,
  SuspendRepository,
} from "@tidecove/services/participants/ports";

export interface ParticipantsDomainModule {
  repos: {
    disputes: DisputeRepository;
    participants: ParticipantRepository;
    resolves: ResolveRepository;
    suspends: SuspendRepository;
  };
  useCases: {
    disputes: {
      get: ExecuteOpenDispute;
      list: ExecuteListDisputes;
    };
    participants: {
      create: ExecuteRegisterParticipant;
      get: ExecuteGetParticipant;
      list: ExecuteListParticipants;
      update: ExecuteUpdateParticipant;
    };
    resolves: {
      get: ExecuteResolveDispute;
    };
    suspends: {
      get: ExecuteSuspendParticipant;
    };
  };
}

export function buildParticipantsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ParticipantsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disputes?: DisputeRepository;
      participants?: ParticipantRepository;
      resolves?: ResolveRepository;
      suspends?: SuspendRepository;
    } = {};

    obj.disputes = new DisputeRepositoryAdapter(dynamoClient);
    obj.participants = new ParticipantRepositoryAdapter(dynamoClient);
    obj.resolves = new ResolveRepositoryAdapter(dynamoClient);
    obj.suspends = new SuspendRepositoryAdapter(dynamoClient);
    return {
      disputes: obj.disputes!,
      participants: obj.participants!,
      resolves: obj.resolves!,
      suspends: obj.suspends!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disputes: {
      get: new ExecuteOpenDispute(executionContext, idGenerator, repos.disputes),
      list: new ExecuteListDisputes(executionContext, idGenerator, repos.disputes),
    },
    participants: {
      create: new ExecuteRegisterParticipant(executionContext, idGenerator, repos.participants),
      get: new ExecuteGetParticipant(executionContext, idGenerator, repos.participants),
      list: new ExecuteListParticipants(executionContext, idGenerator, repos.participants),
      update: new ExecuteUpdateParticipant(executionContext, idGenerator, repos.participants),
    },
    resolves: {
      get: new ExecuteResolveDispute(executionContext, idGenerator, repos.resolves),
    },
    suspends: {
      get: new ExecuteSuspendParticipant(executionContext, idGenerator, repos.suspends),
    },
  };
  return { repos, useCases: useCases as ParticipantsDomainModule["useCases"] };
}
