/**
 * Handlers for Asset
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssetsDomainModule } from "../dependencies/assets-ddd.dependencies.js";
import type { GetAssetInput, ListAssetsInput, PublishAssetInput, UpdateAssetInput } from "@tidecove/services/assets";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/assets
 * Operation: listAssets
 */
export async function listAssets(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], licenceClassHint?: string | string[], gravityBound?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AssetsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAssetsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.assets.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/assets
 * Operation: publishAsset
 */
export async function publishAsset(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AssetsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PublishAssetInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.assets.publish.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/assets/{assetId}
 * Operation: getAsset
 */
export async function getAsset(
  request: FastifyRequest<{ Params: { assetId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssetsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAssetInput = {
    assetId: request.params.assetId,
  };
  const result = await deps.useCases.assets.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/assets/{assetId}
 * Operation: updateAsset
 */
export async function updateAsset(
  request: FastifyRequest<{ Params: { assetId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssetsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateAssetInput = {
    assetId: request.params.assetId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.assets.update.execute(input);
  return reply.code(200).send(result);
}


