/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Assets Domain Use Cases
 * 
 * List of all use case names for the assets domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ASSETS_USE_CASES = [
  "executeGetAsset",
  "executeListAssets",
  "executePublishAsset",
  "executeUpdateAsset"
] as const;
