/**
 * ComplianceTagRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: compliance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplianceTagRepository Port
 *
 * DDD: Application port for compliancetagrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateComplianceTagInput, CreateComplianceTagOutput, GetComplianceTagInput, GetComplianceTagOutput, ListComplianceTagsInput, ListComplianceTagsOutput, UpdateComplianceTagInput, UpdateComplianceTagOutput } from "../dto/compliance-tag.dto";
export interface ComplianceTagRepository {
  listComplianceTags(input: ListComplianceTagsInput): Promise<ListComplianceTagsOutput>;
  createComplianceTag(input: CreateComplianceTagInput): Promise<CreateComplianceTagOutput>;
  getComplianceTag(input: GetComplianceTagInput): Promise<GetComplianceTagOutput>;
  updateComplianceTag(input: UpdateComplianceTagInput): Promise<UpdateComplianceTagOutput>;
}

export type { CreateComplianceTagInput, CreateComplianceTagOutput, GetComplianceTagInput, GetComplianceTagOutput, ListComplianceTagsInput, ListComplianceTagsOutput, UpdateComplianceTagInput, UpdateComplianceTagOutput } from "../dto/compliance-tag.dto";
