/**
 * CancelComputeJob handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { cancelComputeJob } from "@tidecove/api-server/domains/entitlements/handlers";
import type { EntitlementsDDDDependencies } from "@tidecove/api-server/domains/entitlements";
import { createComputeJob as createComputeJobEntity } from "@tidecove/factories/entitlements";
import { createUpdateComputeJobRequest } from "@tidecove/factories/entitlements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { ENTITLEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CancelComputeJob", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EntitlementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EntitlementsDDDDependencies>(
      ENTITLEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createComputeJobEntity({ orgId });
    const input = createUpdateComputeJobRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { jobId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCancelComputeJob, "execute").mockResolvedValue(useCaseResult);

    await cancelComputeJob(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCancelComputeJob.execute).toHaveBeenCalledWith(expect.objectContaining({ jobId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
