/**
 * GetComputeJob handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getComputeJob } from "@tidecove/api-server/domains/entitlements/handlers";
import type { EntitlementsDDDDependencies } from "@tidecove/api-server/domains/entitlements";
import { createComputeJob as createComputeJobEntity } from "@tidecove/factories/entitlements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { ENTITLEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetComputeJob", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EntitlementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EntitlementsDDDDependencies>(
      ENTITLEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createComputeJobEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetComputeJob, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { jobId: entity.id };

    await getComputeJob(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetComputeJob.execute).toHaveBeenCalledWith(expect.objectContaining({ jobId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { jobId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetComputeJob, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getComputeJob(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
