/**
 * ScheduleComputeJob handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: entitlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { scheduleComputeJob } from "@tidecove/api-server/domains/entitlements/handlers";
import type { EntitlementsDDDDependencies } from "@tidecove/api-server/domains/entitlements";
import { createComputeJob as createComputeJobEntity } from "@tidecove/factories/entitlements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tidecove/tests/shared";
import { ENTITLEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ScheduleComputeJob", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EntitlementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EntitlementsDDDDependencies>(
      ENTITLEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createComputeJobEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeScheduleComputeJob, "execute").mockResolvedValue(useCaseResult);

    await scheduleComputeJob(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeScheduleComputeJob.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
