/**
 * MarketplaceFrontRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketplaceFrontRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements MarketplaceFrontRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  MarketplaceFrontRepository,
} from "@tidecove/services/marketplace";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { MarketplaceFrontRepositoryDdb } from "./marketplace-front-repository.ddb.js";

/**
 * MarketplaceFrontRepositoryAdapter
 *
 * Implements MarketplaceFrontRepository port for infrastructure layer.
 */
export class MarketplaceFrontRepositoryAdapter implements MarketplaceFrontRepository {
  private readonly ddb: MarketplaceFrontRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new MarketplaceFrontRepositoryDdb(this.dynamoClient);
  }

  async listMarketplaceFronts(input: Parameters<MarketplaceFrontRepository['listMarketplaceFronts']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['listMarketplaceFronts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listMarketplaceFronts(input);
  }

  async registerMarketplaceFront(input: Parameters<MarketplaceFrontRepository['registerMarketplaceFront']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['registerMarketplaceFront']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerMarketplaceFront(input);
  }

  async getMarketplaceFront(input: Parameters<MarketplaceFrontRepository['getMarketplaceFront']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['getMarketplaceFront']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getMarketplaceFront(input);
  }

  async updateMarketplaceFront(input: Parameters<MarketplaceFrontRepository['updateMarketplaceFront']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['updateMarketplaceFront']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateMarketplaceFront(input);
  }
}
