/**
 * MarketplaceFrontRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketplaceFrontRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing MarketplaceFront repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { MarketplaceFrontRepository } from "@tidecove/services/marketplace";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * MarketplaceFrontRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: MARKETPLACE_FRONT
 * Entity Token: MARKETPLACE_FRONT
 * SK Prefix: MARKETPLACE_FRONT
 */
export class MarketplaceFrontRepositoryDdb implements MarketplaceFrontRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "MARKETPLACE_FRONT";
  private readonly ENTITY_TOKEN = "MARKETPLACE_FRONT";
  private readonly SK_PREFIX = "MARKETPLACE_FRONT";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "MARKETPLACE";
  private readonly ENTITY_TYPE_PK = "MARKETPLACE_FRONTS";
  private generateCorrelationId(): string {
    const domainPrefix = "mkt";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async listMarketplaceFronts(input: Parameters<MarketplaceFrontRepository['listMarketplaceFronts']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['listMarketplaceFronts']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const prefix = this.getCollectionPK(inputExt.orgId as string);
    const rawLimit = inputExt?.limit;
    const parsedLimit = rawLimit == null || rawLimit === ""
      ? 50
      : (typeof rawLimit === "string" ? parseInt(rawLimit as string, 10) : Number(rawLimit));
    const limit = Number.isFinite(parsedLimit) && parsedLimit > 0 ? parsedLimit : 50;
    const result = await this.dynamoClient.scan({
      TableName: this.TABLE_NAME,
      FilterExpression: "begins_with(PK, :prefix)",
      ExpressionAttributeValues: { ":prefix": prefix },
      Limit: limit,
      ...((() => {
        const c = inputExt?.cursor;
        if (!c || (typeof c === "string" && !c.trim())) return {};
        try {
          return {
            ExclusiveStartKey: typeof c === "string"
              ? JSON.parse(Buffer.from(c, "base64").toString())
              : c,
          };
        } catch {
          return {};
        }
      })()),
    });
    const items = ((result.Items || []) as Record<string, unknown>[]).map((i) => sanitizeItem(i));
    return {
      data: { items: items } as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
        pagination: {
          nextCursor: result.LastEvaluatedKey ? Buffer.from(JSON.stringify(result.LastEvaluatedKey)).toString("base64") : null,
          prevCursor: null,
          limit: inputExt?.limit || 50,
        },
      } as unknown as any,
    };
  }

  async registerMarketplaceFront(input: Parameters<MarketplaceFrontRepository['registerMarketplaceFront']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['registerMarketplaceFront']>>> {
    const inputExt = input as Record<string, unknown>;

    const now = new Date().toISOString();
    const orgId = inputExt.orgId;
    const id = inputExt?.id ?? inputExt?.id;
    if (!id) throw new Error("Missing required parameter: id (inject from use case)");
    const pk = this.buildPK(orgId as string, id as string);
    const sk = this.buildSK(id as string);
    const excludedFields = ["id" as string, "id"];
    const inputWithoutId = Object.fromEntries(
      Object.entries(input || {}).filter(([key]) => !excludedFields.includes(key))
    );
    const item = {
      ...inputWithoutId,
      id: id,
      PK: pk,
      SK: sk,
      entityType: this.ENTITY_TYPE,
      [this.CREATED_AT_FIELD]: now,
      [this.UPDATED_AT_FIELD]: now,
    };
    await this.dynamoClient.put({
      TableName: this.TABLE_NAME,
      Item: item,
      ConditionExpression: "attribute_not_exists(PK) AND attribute_not_exists(SK)",
    });
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }

  async getMarketplaceFront(input: Parameters<MarketplaceFrontRepository['getMarketplaceFront']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['getMarketplaceFront']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!(inputExt.id ?? inputExt.frontId)) {
      throw new Error("Missing required parameter: id");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const pk = this.buildPK(inputExt.orgId as string, (inputExt.id ?? inputExt.frontId) as string);
    // Soft-delete layout prefixes SK with ACTIVE# when statusPrefix is enabled.
    const skPrefix = `${this.ENTITY_TOKEN}#${(inputExt.id ?? inputExt.frontId)}#`;
    const result = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": skPrefix },
      Limit: 1,
    });
    const item = result.Items?.[0];
    if (!item) {
      throw new Error(`${this.ENTITY_TYPE} with id ${(inputExt.id ?? inputExt.frontId)} not found`);
    }
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }

  async updateMarketplaceFront(input: Parameters<MarketplaceFrontRepository['updateMarketplaceFront']>[0]): Promise<Awaited<ReturnType<MarketplaceFrontRepository['updateMarketplaceFront']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!inputExt.frontId) {
      throw new Error("Missing required parameter: id");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const pk = this.buildPK(inputExt.orgId as string, inputExt.frontId as string);
    const getResult = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": `${this.ENTITY_TOKEN}#${inputExt.frontId}#` },
      ScanIndexForward: false,
      Limit: 1,
    });
    const existing = getResult.Items?.[0] as Record<string, unknown> | undefined;
    const now = new Date().toISOString();
    if (!existing?.PK || !existing?.SK) {
      // Upsert: create when missing (PUT semantics)
      const pkNew = this.buildPK(inputExt.orgId as string, inputExt.frontId as string);
      const skNew = this.buildSK(inputExt.frontId as string);
      const item = {
        ...(input as Record<string, unknown>),
        id: inputExt.frontId,
        PK: pkNew,
        SK: skNew,
        entityType: this.ENTITY_TYPE,
        [this.CREATED_AT_FIELD]: now,
        [this.UPDATED_AT_FIELD]: now,
        "GSI2-PK": this.buildGSI2PK(inputExt.orgId as string),
        "GSI2-SK": this.buildGsiSK(now, inputExt.frontId as string),
      };
      await this.dynamoClient.put({
        TableName: this.TABLE_NAME,
        Item: item,
      });
      return {
        data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
        meta: {
          correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
          timestamp: new Date().toISOString(),
        } as unknown as any,
      };
    }
    const updateExpressions: string[] = [`#${this.UPDATED_AT_FIELD} = :updatedAt`];
    const expressionAttributeNames: Record<string, string> = { [`#${this.UPDATED_AT_FIELD}`]: this.UPDATED_AT_FIELD };
    const expressionAttributeValues: Record<string, unknown> = { ":updatedAt": now };
    Object.keys(input || {}).forEach((key, index) => {
      if (key !== "id" && key !== "orgId" && key !== "correlationId") {
        const nameKey = `#field${index}`;
        const valueKey = `:value${index}`;
        updateExpressions.push(`${nameKey} = ${valueKey}`);
        expressionAttributeNames[nameKey] = key;
        expressionAttributeValues[valueKey] = inputExt[key];
      }
    });
    const result = await this.dynamoClient.update({
      TableName: this.TABLE_NAME,
      Key: { PK: existing.PK, SK: existing.SK },
      UpdateExpression: `SET ${updateExpressions.join(", ")}`,
      ExpressionAttributeNames: expressionAttributeNames,
      ExpressionAttributeValues: expressionAttributeValues,
      ReturnValues: "ALL_NEW",
    });
    return {
      data: sanitizeItem((result.Attributes || {}) as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
