/**
 * Suspend Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/participants.openapi.types.js";
import { schemas } from "../schemas/participants.schemas.js";

/**
 * Entity: SuspendEntity
 * Description: Represents the Suspend domain model.
 * Source: schemas.Participant
 * Type: Persisted Entity (x-dynamodb)
 */
export const SuspendEntitySchema = schemas.Participant;
export type SuspendEntity = components["schemas"]["Participant"];
