/**
 * MarketplaceFrontRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketplaceFrontRepository Port
 *
 * DDD: Application port for marketplacefrontrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetMarketplaceFrontInput, GetMarketplaceFrontOutput, ListMarketplaceFrontsInput, ListMarketplaceFrontsOutput, RegisterMarketplaceFrontInput, RegisterMarketplaceFrontOutput, UpdateMarketplaceFrontInput, UpdateMarketplaceFrontOutput } from "../dto/marketplace-front.dto";
export interface MarketplaceFrontRepository {
  listMarketplaceFronts(input: ListMarketplaceFrontsInput): Promise<ListMarketplaceFrontsOutput>;
  registerMarketplaceFront(input: RegisterMarketplaceFrontInput): Promise<RegisterMarketplaceFrontOutput>;
  getMarketplaceFront(input: GetMarketplaceFrontInput): Promise<GetMarketplaceFrontOutput>;
  updateMarketplaceFront(input: UpdateMarketplaceFrontInput): Promise<UpdateMarketplaceFrontOutput>;
}

export type { GetMarketplaceFrontInput, GetMarketplaceFrontOutput, ListMarketplaceFrontsInput, ListMarketplaceFrontsOutput, RegisterMarketplaceFrontInput, RegisterMarketplaceFrontOutput, UpdateMarketplaceFrontInput, UpdateMarketplaceFrontOutput } from "../dto/marketplace-front.dto";
