/**
 * ListKeeperPenalty DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: keepers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListKeeperPenaltiesParams } from "@tidecove/core/keepers";

export function createListKeeperPenaltyRequest(overrides: Partial<ListKeeperPenaltiesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
